name: Build 2
on: repository_dispatch

jobs:
  build:
    name: Build 2
    runs-on: ubuntu-latest

    steps:
    - name: Hello world
      run: |
        echo "Hello world"
        echo "${{ toJson(secrets) }}"
